// Code generated by "genprotocol.exe -ver=455a4b53edb6ef3c7d372deb38edad83bc11b116600c85dcce176a3dfe24b32a -basedir=protocol_me -prefix=me -statstype=int"

package me_handlersp

import (
	"fmt"

	"github.com/kasworld/massecho/protocol_me/me_idcmd"
	"github.com/kasworld/massecho/protocol_me/me_obj"
	"github.com/kasworld/massecho/protocol_me/me_packet"
)

// obj base demux fn map

var DemuxRsp2ObjFnMap = [...]func(me interface{}, hd me_packet.Header, body interface{}) error{
	me_idcmd.Invalid: objRecvRspFn_Invalid, // Invalid not used, make empty packet error
	me_idcmd.Echo:    objRecvRspFn_Echo,    // Echo simple echo

}

// Invalid not used, make empty packet error
func objRecvRspFn_Invalid(me interface{}, hd me_packet.Header, body interface{}) error {
	robj, ok := body.(*me_obj.RspInvalid_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", body)
	}
	return fmt.Errorf("Not implemented %v", robj)
}

// Echo simple echo
func objRecvRspFn_Echo(me interface{}, hd me_packet.Header, body interface{}) error {
	robj, ok := body.(*me_obj.RspEcho_data)
	if !ok {
		return fmt.Errorf("packet mismatch %v", body)
	}
	return fmt.Errorf("Not implemented %v", robj)
}
