// Code generated by "genprotocol.exe -ver=455a4b53edb6ef3c7d372deb38edad83bc11b116600c85dcce176a3dfe24b32a -basedir=protocol_me -prefix=me -statstype=int"

package me_obj

// Invalid not used, make empty packet error
type ReqInvalid_data struct {
	Dummy uint8 // change as you need
}

// Invalid not used, make empty packet error
type RspInvalid_data struct {
	Dummy uint8 // change as you need
}

// Echo simple echo
type ReqEcho_data struct {
	Msg string
}

// Echo simple echo
type RspEcho_data struct {
	Msg string
}

// Invalid not used, make empty packet error
type NotiInvalid_data struct {
	Dummy uint8 // change as you need
}
